//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catflap.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts_English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts_English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catflap.Resources.Texts_English", typeof(Texts_English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required.
        /// </summary>
        internal static string binary_updated_restart_required {
            get {
                return ResourceManager.GetString("binary_updated_restart_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The updater needs to restart..
        /// </summary>
        internal static string binary_updated_restart_required_long {
            get {
                return ResourceManager.GetString("binary_updated_restart_required_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy!.
        /// </summary>
        internal static string busy {
            get {
                return ResourceManager.GetString("busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing manifest!.
        /// </summary>
        internal static string busy_manifest {
            get {
                return ResourceManager.GetString("busy_manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} remaining.
        /// </summary>
        internal static string busy_sync_n_need_syncing {
            get {
                return ResourceManager.GetString("busy_sync_n_need_syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string busy_sync_objects_need_syncing {
            get {
                return ResourceManager.GetString("busy_sync_objects_need_syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait!.
        /// </summary>
        internal static string busy_window_title {
            get {
                return ResourceManager.GetString("busy_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot simulate.
        /// </summary>
        internal static string err_cannot_simulate {
            get {
                return ResourceManager.GetString("err_cannot_simulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full verify does not support simulate-mode, sorry!.
        /// </summary>
        internal static string err_cannot_simulate_long {
            get {
                return ResourceManager.GetString("err_cannot_simulate_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been some problem downloading/parsing the repository manifest:\n\n {0}.
        /// </summary>
        internal static string err_manifest_network_failure_exit {
            get {
                return ResourceManager.GetString("err_manifest_network_failure_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve repository manifest: {0} Switching to offline mode..
        /// </summary>
        internal static string err_manifest_network_failure_offline_mode {
            get {
                return ResourceManager.GetString("err_manifest_network_failure_offline_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are problems with the repository manifest (This is probably not your fault, it needs to be fixed in the repository!):\n\n {0}.
        /// </summary>
        internal static string err_manifest_parse_error {
            get {
                return ResourceManager.GetString("err_manifest_parse_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        internal static string mainwindow_button_more {
            get {
                return ResourceManager.GetString("mainwindow_button_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string mainwindow_button_openfolder {
            get {
                return ResourceManager.GetString("mainwindow_button_openfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shortcut.
        /// </summary>
        internal static string mainwindow_button_shortcut {
            get {
                return ResourceManager.GetString("mainwindow_button_shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string mainwindow_button_verify {
            get {
                return ResourceManager.GetString("mainwindow_button_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string mainwindow_logflyout_header {
            get {
                return ResourceManager.GetString("mainwindow_logflyout_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid public key.
        /// </summary>
        internal static string pubkeywindow_button_go_invalid {
            get {
                return ResourceManager.GetString("pubkeywindow_button_go_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save!.
        /// </summary>
        internal static string pubkeywindow_button_go_ok {
            get {
                return ResourceManager.GetString("pubkeywindow_button_go_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter key.
        /// </summary>
        internal static string pubkeywindow_button_go_start {
            get {
                return ResourceManager.GetString("pubkeywindow_button_go_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote repository is signed.
        ///
        ///Please ask the repository maintainer for the public key,
        ///and copy/paste it into this text box..
        /// </summary>
        internal static string pubkeywindow_infotext {
            get {
                return ResourceManager.GetString("pubkeywindow_infotext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This repository is signed.
        /// </summary>
        internal static string pubkeywindow_window_title {
            get {
                return ResourceManager.GetString("pubkeywindow_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote repository is not signed. This is okay if you don&apos;t expect it to be..
        /// </summary>
        internal static string repository_crypto_not_signed_long {
            get {
                return ResourceManager.GetString("repository_crypto_not_signed_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing key mismatch.
        /// </summary>
        internal static string repository_crypto_pubkey_mismatch {
            get {
                return ResourceManager.GetString("repository_crypto_pubkey_mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote repository was signed with a different key than we were expecting.\n\nEither the remote maintainer has changed the signing key,or someone is messing with you (VERY BAD).\n\nContact the repo maintainer! Aborting..
        /// </summary>
        internal static string repository_crypto_pubkey_mismatch_long {
            get {
                return ResourceManager.GetString("repository_crypto_pubkey_mismatch_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote repository is signed, but you are missing the public key locally. We cannot verify that downloaded data has not been tampered with..
        /// </summary>
        internal static string repository_crypto_pubkey_missing_long {
            get {
                return ResourceManager.GetString("repository_crypto_pubkey_missing_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature verification failed.
        /// </summary>
        internal static string repository_crypto_signature_incorrect {
            get {
                return ResourceManager.GetString("repository_crypto_signature_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not verify manifest signature.\n\nEither the signature is out of date, or someone is messing with you (VERY BAD).\n\nContact the repo maintainer! Aborting..
        /// </summary>
        internal static string repository_crypto_signature_incorrect_long {
            get {
                return ResourceManager.GetString("repository_crypto_signature_incorrect_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature missing.
        /// </summary>
        internal static string repository_crypto_signature_missing {
            get {
                return ResourceManager.GetString("repository_crypto_signature_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote repository was signed in the past, but isn&apos;t anymore.\n\nThis means that either the repository maintainer removed the signature, or someone is messing with you (VERY BAD).\n\nContact the repo maintainer! Aborting..
        /// </summary>
        internal static string repository_crypto_signature_missing_long {
            get {
                return ResourceManager.GetString("repository_crypto_signature_missing_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature checks out! We will verify that any downloaded data has not been tampered with in-flight..
        /// </summary>
        internal static string repository_crypto_signature_ok_long {
            get {
                return ResourceManager.GetString("repository_crypto_signature_ok_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature too old.
        /// </summary>
        internal static string repository_crypto_signature_outdated {
            get {
                return ResourceManager.GetString("repository_crypto_signature_outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote repository version is OLDER than the local version.This means that either the repository maintainer messed up, or someone is trying to force you to a older revision.\n\nContact the repo maintainer! Aborting..
        /// </summary>
        internal static string repository_crypto_signature_outdated_long {
            get {
                return ResourceManager.GetString("repository_crypto_signature_outdated_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing key.
        /// </summary>
        internal static string repository_crypto_signing_key {
            get {
                return ResourceManager.GetString("repository_crypto_signing_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string repository_crypto_trusted_comment {
            get {
                return ResourceManager.GetString("repository_crypto_trusted_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository locked..
        /// </summary>
        internal static string repository_locked {
            get {
                return ResourceManager.GetString("repository_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run.
        /// </summary>
        internal static string run_action_run {
            get {
                return ResourceManager.GetString("run_action_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sync.
        /// </summary>
        internal static string run_action_sync {
            get {
                return ResourceManager.GetString("run_action_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing runAction: {0}.
        /// </summary>
        internal static string run_error {
            get {
                return ResourceManager.GetString("run_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nothing to do.
        /// </summary>
        internal static string run_no_action {
            get {
                return ResourceManager.GetString("run_no_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make it go.
        /// </summary>
        internal static string setup_button_go {
            get {
                return ResourceManager.GetString("setup_button_go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected files missing?.
        /// </summary>
        internal static string setup_expected_missing {
            get {
                return ResourceManager.GetString("setup_expected_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This manifest claims it needs to be run in a directory containing certainfiles, but we&apos;re missing the following:\n\n{0}\n\nDo you want to continue anyways?.
        /// </summary>
        internal static string setup_expected_missing_long {
            get {
                return ResourceManager.GetString("setup_expected_missing_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This doesn&apos;t look like a valid repository.
        /// </summary>
        internal static string setup_manifest_invalid {
            get {
                return ResourceManager.GetString("setup_manifest_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving manifest data from {0}: {1}.
        /// </summary>
        internal static string setup_manifest_invalid_long {
            get {
                return ResourceManager.GetString("setup_manifest_invalid_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create desktop shortcut?.
        /// </summary>
        internal static string setup_shortcut_ask {
            get {
                return ResourceManager.GetString("setup_shortcut_ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me to create a desktop shortcut for you?\nI will only ask once. You can this yourself later by clicking &apos;more&apos; in the title bar..
        /// </summary>
        internal static string setup_shortcut_ask_long {
            get {
                return ResourceManager.GetString("setup_shortcut_ask_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untracked files in directory, continue anyways?.
        /// </summary>
        internal static string setup_warn_untracked {
            get {
                return ResourceManager.GetString("setup_warn_untracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS REPOSITORY RECOMMENDS TO START IN A EMPTY DIRECTORY.\n\nYou are setting up in a directory that already contains data that is not tracked by this repository:\n\n{0}\n..\n\nDo you want to continue anyways?.
        /// </summary>
        internal static string setup_warn_untracked_long {
            get {
                return ResourceManager.GetString("setup_warn_untracked_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string setup_window_title {
            get {
                return ResourceManager.GetString("setup_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut created.
        /// </summary>
        internal static string shortcut_created {
            get {
                return ResourceManager.GetString("shortcut_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A shortcut to update &amp; run this repository was created on your Desktop.\n\nFeel free to rename it and/or change the icon..
        /// </summary>
        internal static string shortcut_created_long {
            get {
                return ResourceManager.GetString("shortcut_created_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABORTED.
        /// </summary>
        internal static string status_aborted {
            get {
                return ResourceManager.GetString("status_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABORTED ({0} of actual network traffic).
        /// </summary>
        internal static string status_aborted_n_traffic {
            get {
                return ResourceManager.GetString("status_aborted_n_traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancelled.
        /// </summary>
        internal static string status_cancelled {
            get {
                return ResourceManager.GetString("status_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string status_done {
            get {
                return ResourceManager.GetString("status_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done ({0} of actual network traffic).
        /// </summary>
        internal static string status_done_n_traffic {
            get {
                return ResourceManager.GetString("status_done_n_traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in sync.
        /// </summary>
        internal static string status_n_in_sync {
            get {
                return ResourceManager.GetString("status_n_in_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline mode.
        /// </summary>
        internal static string status_offline {
            get {
                return ResourceManager.GetString("status_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string status_running {
            get {
                return ResourceManager.GetString("status_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} need syncing.
        /// </summary>
        internal static string status_sync_n_need_syncing {
            get {
                return ResourceManager.GetString("status_sync_n_need_syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objects need syncing.
        /// </summary>
        internal static string status_sync_objects_need_syncing {
            get {
                return ResourceManager.GetString("status_sync_objects_need_syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files in {1} sync items, last updated {2}.
        /// </summary>
        internal static string status_sync_tooltip {
            get {
                return ResourceManager.GetString("status_sync_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following items are outdated:.
        /// </summary>
        internal static string status_sync_tooltip_outdated {
            get {
                return ResourceManager.GetString("status_sync_tooltip_outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting directory {0}.
        /// </summary>
        internal static string sync_deleting_directory {
            get {
                return ResourceManager.GetString("sync_deleting_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file {0}.
        /// </summary>
        internal static string sync_deleting_file {
            get {
                return ResourceManager.GetString("sync_deleting_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;deleting leftover file from forced abort: {0}&gt;.
        /// </summary>
        internal static string sync_deleting_leftovers_tmp {
            get {
                return ResourceManager.GetString("sync_deleting_leftovers_tmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash comparison failed for {0}. Expected: {1}, got: {2}.
        /// </summary>
        internal static string sync_hash_comparison_failed {
            get {
                return ResourceManager.GetString("sync_hash_comparison_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hash verification failed.
        /// </summary>
        internal static string sync_hash_failed {
            get {
                return ResourceManager.GetString("sync_hash_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem verifying {0}. This might be a repository error, or someone is messing with your connection. Please contact your repository admin with the contents of this message:\n\n{1}.
        /// </summary>
        internal static string sync_hash_failed_long {
            get {
                return ResourceManager.GetString("sync_hash_failed_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no hash.
        /// </summary>
        internal static string sync_hash_no_hash {
            get {
                return ResourceManager.GetString("sync_hash_no_hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: hash OK({1}).
        /// </summary>
        internal static string sync_hash_ok {
            get {
                return ResourceManager.GetString("sync_hash_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be deleted.
        /// </summary>
        internal static string sync_will_be_deleted {
            get {
                return ResourceManager.GetString("sync_will_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space?.
        /// </summary>
        internal static string warn_disk_space {
            get {
                return ResourceManager.GetString("warn_disk_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to be running out of disk space on {0}. Advanced calculations indicate you might not be able to sync everything: \n\n{1} free, but \n{2} needed (plus change for temporary files).\n\nDo you still want to sync?.
        /// </summary>
        internal static string warn_disk_space_long {
            get {
                return ResourceManager.GetString("warn_disk_space_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify?.
        /// </summary>
        internal static string warn_verify {
            get {
                return ResourceManager.GetString("warn_verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running a full sync will take longer, since it will verify checksums.\n\nThis is usually not needed, except when you suspect corruption. You can cancel at any time.\n\nAre you sure this is what you want?.
        /// </summary>
        internal static string warn_verify_long {
            get {
                return ResourceManager.GetString("warn_verify_long", resourceCulture);
            }
        }
    }
}
